import { createContext, useContext, useEffect, useState } from 'react'

const T = {
  en: {
    appName:'Paddy AI System',appTagline:'AI-Powered Crop Management for Sri Lanka',
    dashboard:'Dashboard',suitability:'Land Suitability',disease:'Disease Detection',
    irrigation:'Irrigation',history:'History',logout:'Logout',profile:'Profile',
    login:'Sign In',register:'Register',email:'Email Address',password:'Password',
    fullName:'Full Name',namePlaceholder:'Your full name',emailPlaceholder:'farmer@example.com',
    passwordPlaceholder:'Min 6 characters',createAccount:'Create Account',signIn:'Sign In',
    goodMorning:'Good Morning',goodAfternoon:'Good Afternoon',goodEvening:'Good Evening',
    dashboardSub:'AI-powered paddy crop management — Sri Lanka',
    quickAccess:'Quick Access',tryNow:'Try Now',
    suitabilityDesc:'Check if your land is suitable for paddy cultivation',
    diseaseDesc:'Upload leaf image to detect paddy diseases instantly',
    irrigationDesc:'Get irrigation recommendations based on conditions',
    aboutSystem:'About This System',
    aboutText:'AI decision support for Sri Lankan paddy farmers using Random Forest, CNN & Gradient Boosting.',
    suitabilityTitle:'Paddy Suitability Prediction',suitabilitySub:'Enter farm data to check suitability',
    environmentParams:'Environmental Parameters',temperature:'Temperature (°C)',
    rainfall:'Rainfall (mm)',soilPh:'Soil pH',humidity:'Humidity (%)',soilType:'Soil Type',
    predictSuitability:'Predict Suitability',predicting:'Predicting...',idealConditions:'Ideal Paddy Conditions',
    suitableResult:'Suitable for Paddy',notSuitableResult:'Not Suitable',
    riskLevel:'Risk Level',confidence:'Confidence',recommendation:'Recommendation',
    diseaseTitle:'Paddy Disease Detection',diseaseSub:'Upload leaf image — CNN will detect disease',
    uploadImage:'Upload Leaf Image',detectDisease:'Detect Disease',detecting:'Analyzing...',
    detectedDisease:'Detected Disease',healthyLeaf:'Healthy Leaf',severity:'Severity',
    treatment:'Treatment',prevention:'Prevention',detectableDiseases:'Detectable Diseases',
    dragDrop:'Drag & drop paddy leaf image',browseImage:'Browse Image',imageReady:'Image ready',
    irrigationTitle:'Irrigation Recommendation',irrigationSub:'Enter field conditions',
    fieldConditions:'Field Conditions',soilMoisture:'Soil Moisture (%)',cropStage:'Crop Growth Stage',
    getAdvice:'Get Irrigation Advice',analyzing:'Analyzing...',
    irrigationStatus:'Irrigation Status',irrigationRequired:'Irrigation Required',
    noIrrigation:'No Irrigation Needed',urgency:'Urgency',
    recommendedWater:'Recommended Water',nextCheck:'Next Check In',waterNeeds:'Water Needs by Stage',
    historyTitle:'Prediction History',historySub:'All your AI predictions',
    noPredictions:'No predictions yet.',predictionResult:'Prediction Result',
    fillForm:'Fill form and click',result:'Result',days:'day(s)',mm:'mm',
    records:'records',successRate:'Success Rate',weeklyActivity:'Weekly Activity',
    last7days:'Last 7 days',predictions:'predictions',totalPredictions:'Total Predictions',
    myProfile:'My Profile',profileSub:'Manage your farm profile and preferences',
    editProfile:'Edit Profile',saveProfile:'Save Profile',farmDetails:'Farm Details',
    farmLocation:'Farm Location',farmSize:'Farm Size',farmBio:'Farm Description',
    fertilizer:'Fertilizer',fertilizerTitle:'Fertilizer Recommendation',fertilizerSub:'Enter soil & nutrient data for the optimal fertilizer',
    soilNutrientParams:'Soil & Nutrient Parameters',
    nitrogen:'Nitrogen (N)',potassium:'Potassium (K)',phosphorous:'Phosphorous (P)',
    getFertilizerAdvice:'Get Fertilizer Advice',recommendedFertilizer:'Recommended Fertilizer',
    quantityRequired:'Quantity Required',applicationSchedule:'Application Schedule',organicAlternative:'Organic Alternative',
    yield:'Yield Prediction',yieldTitle:'Paddy Yield Prediction',yieldSub:'Enter cultivation data to estimate harvest',
    cultivationParams:'Cultivation Parameters',fertilizerUsed:'Fertilizer Used (kg/acre)',
    seedVariety:'Seed Variety',irrigationPattern:'Irrigation Pattern',diseaseStatus:'Disease Status',soilQuality:'Soil Quality',
    predictYield:'Predict Yield',estimatedYield:'Estimated Yield',expectedHarvest:'Expected Harvest',productionEfficiency:'Production Efficiency',
    pest:'Pest Risk',pestTitle:'Pest Risk Prediction',pestSub:'Enter field conditions to assess pest risk',
    rainfall7d:'Rainfall Last 7 Days (mm)',checkPestRisk:'Check Pest Risk',pestRiskLevel:'Pest Risk Level',
    mostLikelyPest:'Most Likely Pest',preventionMeasures:'Prevention Measures',recommendedPesticide:'Recommended Pesticide',organicOption:'Organic Option',
    fertilizerDesc:'Get NPK-based fertilizer recommendations',yieldDesc:'Estimate your expected harvest yield',pestDesc:'Assess pest infestation risk for your field',
    weather:'Weather Advisory',weatherTitle:'Weather-Based Farming Advisory',weatherSub:'Get planting, fertilizer & irrigation guidance based on weather',
    weatherConditions:'Weather Conditions',rainfallForecast:'Rainfall Forecast (mm)',getWeatherAdvisory:'Get Weather Advisory',
    bestPlantingTime:'Planting Advice',fertilizerTiming:'Fertilizer Timing',irrigationTiming:'Irrigation Timing',harvestPlanning:'Harvest Planning',weatherAlerts:'Alerts',
    weatherDesc:'Weather-based planting, fertilizer & irrigation guidance',farmManagement:'My Farms',farmManagementDesc:'Register farms and track cultivation activities',
// Extended UI, validation and accessibility translations
adminPanel:'Admin Panel',administrator:'Administrator',systemAdministration:'System Administration',
adminSub:'Manage users, review every AI prediction type and monitor application services.',
overview:'Overview',users:'Users',refresh:'Refresh',predictionBreakdown:'Prediction Breakdown',serviceConfiguration:'Service Configuration',
recentPredictions:'Recent Predictions (Last 10)',noAdminPredictions:'No predictions have been created yet.',
totalUsers:'Total Users',registeredAccounts:'Registered accounts',allModelTypes:'All model types',diseaseScans:'Disease Scans',leafImageScans:'Leaf image scans',farmerValidatedAccuracy:'Farmer-Validated Accuracy',noFeedbackYet:'No feedback yet',
name:'Name',role:'Role',joined:'Joined',actions:'Actions',promote:'Promote',demote:'Demote',delete:'Delete',status:'Status',
javaBackend:'Java Backend',reactFrontend:'React Frontend',mysqlDb:'MySQL DB',pythonMlApi:'Python ML API',responding:'Responding',currentApp:'Current app',backendConnected:'Backend connected',usedOnPredictions:'Used on predictions',
notifications:'Notifications',markAllRead:'Mark all read',noNotifications:'No notifications yet',justNow:'just now',
farmManagementTitle:'Farm Management',myFarms:'My Farms',farmManagementSub:'Register fields, track crop variety & log farm activities',
addFarm:'Add Farm',editFarm:'Edit Farm',newFarm:'New Farm',farmName:'Farm Name',location:'Location',sizeAcres:'Size (acres)',currentCropVariety:'Current Crop Variety',plantingDate:'Planting Date',notes:'Notes',saveChanges:'Save Changes',
loadingFarms:'Loading farms...',noFarms:'No farms registered yet.',viewActivities:'View Activities',activitiesShown:'Activities Shown Below',activityLog:'Activity Log',logActivity:'Log Activity',activityType:'Activity Type',date:'Date',description:'Description',saveActivity:'Save Activity',noActivities:'No activities logged yet.',
farmAdded:'Farm added!',farmUpdated:'Farm updated!',farmDeleted:'Farm deleted',activityLogged:'Activity logged!',activityDeleted:'Activity deleted',failedSaveFarm:'Failed to save farm.',failedDeleteFarm:'Failed to delete farm.',failedLogActivity:'Failed to log activity.',failedDeleteActivity:'Failed to delete activity.',
confirmDeleteFarm:'Delete this farm and all its activity records?',confirmDeleteUser:'Delete this user and all related data? This cannot be undone.',
invalidDiseaseFile:'Only JPG, JPEG, PNG or WebP image files are accepted.',imageTooLarge:'Image must be 5 MB or smaller.',selectLeafFirst:'Please select a leaf image first.',diseaseComplete:'Disease analysis complete!',detectionFailed:'Detection failed.',mlServerDown:'ML server is not running. Start the Python service on port 8000.',supportedImages:'JPG · JPEG · PNG · WebP accepted',or:'or',betterScanTips:'Better Scan Tips',
scanTip1:'Take the photo in bright natural daylight',scanTip2:'Focus clearly on the affected leaf area',scanTip3:'Avoid blurry or dark photos',scanTip4:'Use one leaf per scan for best accuracy',
uploadPrompt:'Upload a paddy leaf photo and click Detect Disease',cnnAnalyze:'The CNN model will analyze the leaf',changeImage:'Change Image',remove:'Remove',
forgotTagline:'Forgot your password?',backToSignIn:'Back to sign in',checkInbox:'Check your inbox',resetPassword:'Reset your password',resetHelp:'Enter your email and we will send a link to get back into your account.',sendResetLink:'Send Reset Link',tryAgain:'Did not get it? Try again',resetEmailSent:'Password reset email request sent.',
invalidResetTagline:'Link looks invalid',invalidResetLink:'Invalid reset link',invalidResetHelp:'This link is missing its reset token. Please request a new password reset link.',requestNewLink:'Request New Link',setNewPassword:'Set a new password',passwordResetDone:'Password reset!',passwordChanged:'Your password has been changed successfully.',createNewPassword:'Create new password',strongPasswordHelp:'Make it strong — at least 6 characters.',newPassword:'New password',confirmNewPassword:'Confirm new password',passwordsMismatch:'Passwords do not match.',passwordMin:'Password must be at least 6 characters.',resetFailed:'Failed to reset password. The link may have expired.',
sessionExpired:'Your session has expired. Please sign in again.',networkError:'Cannot reach the server. Check that the backend is running.',requestTimeout:'The request timed out. Please try again.',
adminLoadFailed:'Failed to load admin data',selfRoleBlocked:'You cannot change your own admin role while signed in.',selfDeleteBlocked:'You cannot delete the account you are currently using.',roleChanged:'Role changed successfully',userDeleted:'User deleted',roleChangeFailed:'Failed to change role',userDeleteFailed:'Failed to delete user',
historyHeading:'Prediction History',historyAll:'All your AI predictions in one place',noRecordsExport:'No records to export',pdfDownloaded:'PDF downloaded',feedbackSaveFailed:'Could not save feedback',
predictionAccurateQuestion:'Was this prediction accurate?',yes:'Yes',no:'No',markedAccurate:'Marked accurate',feedbackRecorded:'Feedback recorded',lowConfidence:'Low confidence result.',aiConfidence:'AI Confidence',forPaddy:'for paddy cultivation',analysis:'Analysis',notesLabel:'Notes',chemicalOption:'Chemical Option',alerts:'Alerts',howToUse:'How to use',
profileSaved:'Profile saved!',profileSaveFailed:'Could not save profile. Please try again.',invalidAvatar:'Please choose a JPG, PNG or WebP image',avatarTooLarge:'Image must be under 5MB',avatarProcessFailed:'Could not process that image. Please choose another photo.',
deleteSuccess:'Deleted successfully',operationFailed:'Operation failed. Please try again.',
    welcomeBack:'Welcome back',createYourAccount:'Create your account',loginSub:'Sign in to manage your paddy fields',registerSub:'Start growing smarter, for free',forgotPassword:'Forgot password?',dontHaveAccount:'Don’t have an account?',alreadyHaveAccount:'Already have an account?',signUp:'Sign up',showPassword:'Show password',hidePassword:'Hide password',allUsers:'All Users',allPredictions:'All Predictions',type:'Type',userLabel:'User',unknownUser:'Unknown user',unnamedUser:'Unnamed user',you:'You',loading:'Loading...',ratedAccurate:'rated accurate',total:'Total',successRateAll:'Success Rate — All Models',successRateHelp:'Based on your accuracy feedback on each prediction below',
    suitabilityResultLabel:'Suitability Result',diseaseScanResult:'Disease Scan Result',severityLevel:'Severity Level',recommendedFertilizerLabel:'Recommended Fertilizer',estimatedYieldLabel:'Estimated Yield',pestRiskLabel:'Pest Risk Level',chemicalOptionLabel:'Chemical Option',organicOptionLabel:'Organic Option',seedling:'Seedling',vegetative:'Vegetative',flowering:'Flowering',ripening:'Ripening',clay:'Clay',loam:'Loam',sandy:'Sandy',profileStrength:'Profile Strength',saving:'Saving...',editProfileHint:'Click Edit Profile on the left to update your details',mlServerInactive:'The Python ML server is not active. Start it to use AI predictions.',mlServerAfterStart:'After starting, the server runs on',cropManagement:'Crop Management',designedBy:'Designed & Developed by',predictionCompleteMsg:'Prediction complete!',analysisCompleteMsg:'Analysis complete!',recommendationReadyMsg:'Recommendation ready!',yieldEstimatedMsg:'Yield estimated!',riskAssessedMsg:'Risk assessed!',advisoryReadyMsg:'Advisory ready!',predictionFailedMsg:'Prediction failed.',

    makePredictionsChart:'Make predictions to see chart',languageLabel:'Language / භාෂාව / மொழி',weeklyActivity7:'Weekly Activity (Last 7 Days)',predictionsThisWeek:'predictions this week',recentActivity:'Recent Activity',recentEmpty:'No predictions yet — try Suitability, Disease, or Irrigation to see activity here.',allTime:'All time',landChecks:'Land checks',leafScans:'Leaf scans',fieldAdvices:'Field advices',recommendations:'Recommendations',estimates:'Estimates',riskChecks:'Risk checks',advisories:'Advisories',uploadPaddyLeafImage:'Upload Paddy Leaf Image',forgotSentPrefix:'If an account exists for',forgotSentSuffix:'we have sent a link to reset your password. The link expires in 30 minutes.',emailExample:'you@example.com',exportPdf:'Export PDF',goodOutcome:'Good outcome — no action needed',attentionNeeded:'Attention needed',accurate:'Accurate',inaccurate:'Inaccurate',completeFarmDetails:'Complete your farm details for better AI recommendations',soil:'Soil',farmer:'Farmer',loadingProfile:'Loading profile…',cancel:'Cancel',acres:'acres',selectSoilType:'Select soil type',describeFarmPlaceholder:'Describe your farm...',farmActivity:'Farm Activity',totalAiPredictions:'Total AI Predictions',lastActive:'Last Active',farmNamePlaceholder:'e.g. Kurunegala Paddy Field',farmLocationPlaceholder:'e.g. Kurunegala, NW Province',additionalNotesPlaceholder:'Any additional notes...',activityDescriptionPlaceholder:'e.g. Applied Urea top-dress, 45kg/acre',feedbackThanksAccurate:'Thanks! Marked as accurate.',feedbackThanksRecorded:'Thanks for the feedback — noted.',aiFocusMap:'AI Focus Map (Grad-CAM)',aiFocusHelp:'Red/yellow areas show where the AI model focused most when making this diagnosis.',symptomsToLookFor:'Symptoms to look for',treatmentGuide:'Treatment guide',step:'Step',preventionTips:'Prevention tips',uploadProfilePhoto:'Upload profile photo',removePhoto:'Remove photo',
    lowConfidenceHelp:'The AI is not very sure about this prediction (below 60%). Re-check the input or image and confirm important actions with a local agriculture officer.',planted:'Planted',
    active:'Active',
  },
  si: {
    appName:'Paddy AI System',appTagline:'ශ්‍රී ලංකාව සඳහා AI-බල ගත් බෝග කළමනාකරණය',
    dashboard:'උපකරණ පුවරුව',suitability:'ඉඩම් යෝග්‍යතාව',disease:'රෝග හඳුනාගැනීම',
    irrigation:'ජල සම්පාදනය',history:'ඉතිහාසය',logout:'ඉවත් වන්න',profile:'පැතිකඩ',
    login:'ඇතුළු වන්න',register:'ලියාපදිංචි වන්න',email:'විද්‍යුත් තැපෑල',password:'මුරපදය',
    fullName:'සම්පූර්ණ නම',namePlaceholder:'ඔබේ සම්පූර්ණ නම',emailPlaceholder:'farmer@example.com',
    passwordPlaceholder:'අවම අක්ෂර 6',createAccount:'ගිණුම සාදන්න',signIn:'ඇතුළු වන්න',
    goodMorning:'සුබ උදෑසනක්',goodAfternoon:'සුබ දහවලක්',goodEvening:'සුබ සන්ධ්‍යාවක්',
    dashboardSub:'AI-බල ගත් වී බෝග කළමනාකරණ — ශ්‍රී ලංකාව',
    quickAccess:'ඉක්මන් ප්‍රවේශය',tryNow:'දැන් උත්සාහ කරන්න',
    suitabilityDesc:'ඔබේ ඉඩම වී වගාවට යෝග්‍යද පරීක්ෂා කරන්න',
    diseaseDesc:'වී රෝග හඳුනා ගැනීමට කොළ රූපය උඩු දමන්න',
    irrigationDesc:'ජල සම්පාදන නිර්දේශ ලබා ගන්න',
    aboutSystem:'මෙම පද්ධතිය ගැන',
    aboutText:'ශ්‍රී ලාංකික වී ගොවීන් සඳහා AI තීරණ සහාය.',
    suitabilityTitle:'වී යෝග්‍යතා පුරෝකථනය',suitabilitySub:'ඉඩම් යෝග්‍යතාව සඳහා දත්ත ඇතුළු කරන්න',
    environmentParams:'පාරිසරික පරාමිතීන්',temperature:'උෂ්ණත්වය (°C)',
    rainfall:'වර්ෂාපතනය (mm)',soilPh:'පස් pH',humidity:'ආර්ද්‍රතාවය (%)',soilType:'පස් වර්ගය',
    predictSuitability:'යෝග්‍යතාව පුරෝකථනය',predicting:'පුරෝකථනය...',idealConditions:'සුදුසු තත්ත්ව',
    suitableResult:'වී වගාවට යෝග්‍යයි',notSuitableResult:'යෝග්‍ය නොවේ',
    riskLevel:'අවදානම් මට්ටම',confidence:'විශ්වාසය',recommendation:'නිර්දේශය',
    diseaseTitle:'වී රෝග හඳුනාගැනීම',diseaseSub:'CNN රෝගය හඳුනා ගනු ඇත',
    uploadImage:'කොළ රූපය',detectDisease:'රෝගය හඳුනා ගන්න',detecting:'විශ්ලේෂණය...',
    detectedDisease:'හඳුනාගත් රෝගය',healthyLeaf:'සෞඛ්‍ය සම්පන්න කොළ',severity:'බරපතලකම',
    treatment:'ප්‍රතිකාරය',prevention:'වැළැක්වීම',detectableDiseases:'හඳුනාගත හැකි රෝග',
    dragDrop:'කොළ රූපය ඇදගෙන දමන්න',browseImage:'රූපය බ්‍රවුස්',imageReady:'රූපය සූදානම්',
    irrigationTitle:'ජල සම්පාදන නිර්දේශය',irrigationSub:'ක්ෂේත්‍ර තත්ත්ව ඇතුළු කරන්න',
    fieldConditions:'ක්ෂේත්‍ර තත්ත්ව',soilMoisture:'පස් ආර්ද්‍රතාවය (%)',cropStage:'බෝගයේ අදියර',
    getAdvice:'ජල සම්පාදන උපදෙස්',analyzing:'විශ්ලේෂණය...',
    irrigationStatus:'ජල සම්පාදන තත්ත්වය',irrigationRequired:'ජල සම්පාදනය අවශ්‍යයි',
    noIrrigation:'ජල සම්පාදනය අවශ්‍ය නැත',urgency:'හදිසිය',
    recommendedWater:'නිර්දේශිත ජලය',nextCheck:'ඊළඟ පරීක්ෂාව',waterNeeds:'ජල අවශ්‍යතා',
    historyTitle:'පුරෝකථන ඉතිහාසය',historySub:'සියලු AI පුරෝකථන',
    noPredictions:'තවම පුරෝකථන නැත.',predictionResult:'ප්‍රතිඵලය',
    fillForm:'පෝරමය පුරවා ක්ලික් කරන්න',result:'ප්‍රතිඵලය',days:'දිනය',mm:'mm',
    records:'වාර්තා',successRate:'සාර්ථකත්ව අනුපාතය',weeklyActivity:'සතිපතා ක්‍රියාකාරිත්වය',
    last7days:'පසුගිය දින 7',predictions:'පුරෝකථන',totalPredictions:'මුළු පුරෝකථන',
    myProfile:'මගේ පැතිකඩ',profileSub:'ගොවිතැන් පැතිකඩ කළමනාකරණය',
    editProfile:'පැතිකඩ සංස්කරණය',saveProfile:'පැතිකඩ සුරකින්න',farmDetails:'ගොවිතැන් විස්තර',
    farmLocation:'ගොවිපළ පිහිටීම',farmSize:'ගොවිපළ ප්‍රමාණය',farmBio:'ගොවිතැන් විස්තරය',
    fertilizer:'පොහොර',fertilizerTitle:'පොහොර නිර්දේශය',fertilizerSub:'හොඳම පොහොර සඳහා පස් හා පෝෂක දත්ත ඇතුළත් කරන්න',
    soilNutrientParams:'පස් හා පෝෂක පරාමිතීන්',
    nitrogen:'නයිට්‍රජන් (N)',potassium:'පොටෑසියම් (K)',phosphorous:'පොස්පරස් (P)',
    getFertilizerAdvice:'පොහොර උපදෙස් ලබාගන්න',recommendedFertilizer:'නිර්දේශිත පොහොර',
    quantityRequired:'අවශ්‍ය ප්‍රමාණය',applicationSchedule:'යෙදීමේ කාලසටහන',organicAlternative:'කාබනික විකල්පය',
    yield:'අස්වැන්න පුරෝකථනය',yieldTitle:'වී අස්වැන්න පුරෝකථනය',yieldSub:'අස්වැන්න ඇස්තමේන්තු කිරීමට වගා දත්ත ඇතුළත් කරන්න',
    cultivationParams:'වගා පරාමිතීන්',fertilizerUsed:'භාවිතා කළ පොහොර (kg/අක්කරය)',
    seedVariety:'බීජ ප්‍රභේදය',irrigationPattern:'වාරි රටාව',diseaseStatus:'රෝග තත්ත්වය',soilQuality:'පස් ගුණාත්මකභාවය',
    predictYield:'අස්වැන්න පුරෝකථනය කරන්න',estimatedYield:'ඇස්තමේන්තුගත අස්වැන්න',expectedHarvest:'අපේක්ෂිත අස්වනු කාලය',productionEfficiency:'නිෂ්පාදන කාර්යක්ෂමතාව',
    pest:'පළිබෝධ අවදානම',pestTitle:'පළිබෝධ අවදානම් පුරෝකථනය',pestSub:'පළිබෝධ අවදානම තක්සේරු කිරීමට ක්ෂේත්‍ර තත්ත්ව ඇතුළත් කරන්න',
    rainfall7d:'පසුගිය දින 7ක වර්ෂාපතනය (mm)',checkPestRisk:'පළිබෝධ අවදානම පරීක්ෂා කරන්න',pestRiskLevel:'පළිබෝධ අවදානම් මට්ටම',
    mostLikelyPest:'ඉඩ ඇති පළිබෝධය',preventionMeasures:'වැළැක්වීමේ ක්‍රම',recommendedPesticide:'නිර්දේශිත පළිබෝධනාශකය',organicOption:'කාබනික විකල්පය',
    fertilizerDesc:'NPK පදනම් කරගත් පොහොර නිර්දේශ ලබාගන්න',yieldDesc:'ඔබේ අපේක්ෂිත අස්වැන්න ඇස්තමේන්තු කරන්න',pestDesc:'ඔබේ ක්ෂේත්‍රයේ පළිබෝධ අවදානම තක්සේරු කරන්න',
    weather:'කාලගුණ උපදේශනය',weatherTitle:'කාලගුණ පදනම් වූ ගොවිතැන් උපදේශනය',weatherSub:'කාලගුණය මත පදනම්ව රෝපණ, පොහොර හා වාරි මගපෙන්වීම ලබාගන්න',
    weatherConditions:'කාලගුණ තත්ත්ව',rainfallForecast:'වර්ෂාපතන අනාවැකිය (mm)',getWeatherAdvisory:'කාලගුණ උපදෙස් ලබාගන්න',
    bestPlantingTime:'රෝපණ උපදෙස්',fertilizerTiming:'පොහොර කාලය',irrigationTiming:'වාරි කාලය',harvestPlanning:'අස්වනු සැලසුම්',weatherAlerts:'අනතුරු ඇඟවීම්',
    weatherDesc:'කාලගුණය පදනම් වූ රෝපණ, පොහොර හා වාරි මගපෙන්වීම',farmManagement:'මගේ ගොවිපළවල්',
adminPanel:'පරිපාලක පැනලය',administrator:'පරිපාලක',systemAdministration:'පද්ධති පරිපාලනය',adminSub:'පරිශීලකයන්, AI පුරෝකථන සහ සේවා තත්ත්ව කළමනාකරණය කරන්න.',overview:'සාරාංශය',users:'පරිශීලකයන්',refresh:'යාවත්කාලීන',predictionBreakdown:'පුරෝකථන විග්‍රහය',serviceConfiguration:'සේවා සැකසුම්',recentPredictions:'මෑත පුරෝකථන (අවසන් 10)',noAdminPredictions:'තවම පුරෝකථන නොමැත.',totalUsers:'මුළු පරිශීලකයන්',registeredAccounts:'ලියාපදිංචි ගිණුම්',allModelTypes:'සියලු මාදිලි',diseaseScans:'රෝග ස්කෑන්',leafImageScans:'කොළ රූප ස්කෑන්',farmerValidatedAccuracy:'ගොවි තහවුරු නිරවද්‍යතාව',noFeedbackYet:'තවම ප්‍රතිචාර නැත',name:'නම',role:'භූමිකාව',joined:'එක්වූ දිනය',actions:'ක්‍රියා',promote:'උසස් කරන්න',demote:'පහත දමන්න',delete:'මකන්න',status:'තත්ත්වය',javaBackend:'Java පසුපස සේවාව',reactFrontend:'React ඉදිරිපස',mysqlDb:'MySQL දත්තගබඩාව',pythonMlApi:'Python ML API',responding:'ප්‍රතිචාර දක්වයි',currentApp:'වත්මන් යෙදුම',backendConnected:'පසුපස සේවාව සම්බන්ධයි',usedOnPredictions:'පුරෝකථන සඳහා භාවිතයි',notifications:'දැනුම්දීම්',markAllRead:'සියල්ල කියවූ ලෙස සලකන්න',noNotifications:'දැනුම්දීම් නැත',justNow:'දැන්',farmManagementTitle:'ගොවිපළ කළමනාකරණය',myFarms:'මගේ ගොවිපළවල්',farmManagementSub:'ක්ෂේත්‍ර ලියාපදිංචි කර වගා ක්‍රියාකාරකම් සටහන් කරන්න',addFarm:'ගොවිපළ එක් කරන්න',editFarm:'ගොවිපළ සංස්කරණය',newFarm:'නව ගොවිපළ',farmName:'ගොවිපළ නම',location:'ස්ථානය',sizeAcres:'ප්‍රමාණය (අක්කර)',currentCropVariety:'වත්මන් වී ප්‍රභේදය',plantingDate:'රෝපණ දිනය',notes:'සටහන්',saveChanges:'වෙනස්කම් සුරකින්න',loadingFarms:'ගොවිපළ පූරණය වෙමින්...',noFarms:'තවම ගොවිපළ ලියාපදිංචි කර නැත.',viewActivities:'ක්‍රියාකාරකම් බලන්න',activitiesShown:'ක්‍රියාකාරකම් පහතින්',activityLog:'ක්‍රියාකාරකම් සටහන',logActivity:'ක්‍රියාකාරකමක් සටහන් කරන්න',activityType:'ක්‍රියා වර්ගය',date:'දිනය',description:'විස්තරය',saveActivity:'ක්‍රියාකාරකම සුරකින්න',noActivities:'තවම ක්‍රියාකාරකම් නැත.',farmAdded:'ගොවිපළ එක් කරන ලදී!',farmUpdated:'ගොවිපළ යාවත්කාලීන කරන ලදී!',farmDeleted:'ගොවිපළ මකා දමන ලදී',activityLogged:'ක්‍රියාකාරකම සටහන් විය!',activityDeleted:'ක්‍රියාකාරකම මකා දමන ලදී',failedSaveFarm:'ගොවිපළ සුරැකීමට නොහැකි විය.',failedDeleteFarm:'ගොවිපළ මැකීමට නොහැකි විය.',failedLogActivity:'ක්‍රියාකාරකම සටහන් කිරීමට නොහැකි විය.',failedDeleteActivity:'ක්‍රියාකාරකම මැකීමට නොහැකි විය.',confirmDeleteFarm:'මෙම ගොවිපළ සහ සියලු ක්‍රියාකාරකම් මකන්නද?',confirmDeleteUser:'මෙම පරිශීලකයා සහ සම්බන්ධ දත්ත මකන්නද?',invalidDiseaseFile:'JPG, JPEG, PNG හෝ WebP රූප පමණක් පිළිගනී.',imageTooLarge:'රූපය 5 MB හෝ අඩු විය යුතුය.',selectLeafFirst:'පළමුව වී කොළ රූපයක් තෝරන්න.',diseaseComplete:'රෝග විශ්ලේෂණය සම්පූර්ණයි!',detectionFailed:'හඳුනාගැනීම අසාර්ථකයි.',mlServerDown:'ML සේවාදායකය ක්‍රියාත්මක නොවේ. Python සේවාව port 8000 හි ආරම්භ කරන්න.',supportedImages:'JPG · JPEG · PNG · WebP පිළිගනී',or:'හෝ',betterScanTips:'හොඳ ස්කෑන් උපදෙස්',scanTip1:'දීප්තිමත් ස්වභාවික ආලෝකයේ ඡායාරූප ගන්න',scanTip2:'බලපෑ කොළ ප්‍රදේශය පැහැදිලිව නාභිගත කරන්න',scanTip3:'අඳුරු හෝ නොපැහැදිලි රූප වලක්වන්න',scanTip4:'හොඳ නිරවද්‍යතාව සඳහා එක් කොළයක් භාවිතා කරන්න',uploadPrompt:'වී කොළ රූපයක් උඩුගත කර රෝගය හඳුනා ගන්න ක්ලික් කරන්න',cnnAnalyze:'CNN මාදිලිය කොළය විශ්ලේෂණය කරයි',changeImage:'රූපය වෙනස් කරන්න',remove:'ඉවත් කරන්න',forgotTagline:'මුරපදය අමතකද?',backToSignIn:'ඇතුළු වීමට ආපසු',checkInbox:'ඔබේ විද්‍යුත් තැපෑල බලන්න',resetPassword:'මුරපදය නැවත සකසන්න',resetHelp:'ඔබේ විද්‍යුත් තැපෑල ඇතුළත් කරන්න; නැවත සැකසීමේ සබැඳියක් යවමු.',sendResetLink:'නැවත සැකසීමේ සබැඳිය යවන්න',tryAgain:'ලැබුණේ නැද්ද? නැවත උත්සාහ කරන්න',resetEmailSent:'මුරපද නැවත සැකසීමේ ඉල්ලීම යවන ලදී.',invalidResetTagline:'සබැඳිය වලංගු නොවේ',invalidResetLink:'වලංගු නොවන නැවත සැකසීමේ සබැඳිය',invalidResetHelp:'මෙම සබැඳියේ token එක නොමැත. නව සබැඳියක් ඉල්ලන්න.',requestNewLink:'නව සබැඳියක් ඉල්ලන්න',setNewPassword:'නව මුරපදයක් සකසන්න',passwordResetDone:'මුරපදය නැවත සකසා ඇත!',passwordChanged:'ඔබේ මුරපදය සාර්ථකව වෙනස් විය.',createNewPassword:'නව මුරපදයක් සාදන්න',strongPasswordHelp:'අවම වශයෙන් අක්ෂර 6ක් භාවිතා කරන්න.',newPassword:'නව මුරපදය',confirmNewPassword:'නව මුරපදය තහවුරු කරන්න',passwordsMismatch:'මුරපද දෙක නොගැලපේ.',passwordMin:'මුරපදය අවම අක්ෂර 6ක් විය යුතුය.',resetFailed:'මුරපදය නැවත සැකසීමට නොහැකි විය. සබැඳිය කල් ඉකුත්වී තිබිය හැක.',sessionExpired:'ඔබේ සැසිය කල් ඉකුත්වී ඇත. නැවත ඇතුළු වන්න.',networkError:'සේවාදායකයට සම්බන්ධ විය නොහැක. Backend ක්‍රියාත්මකද පරීක්ෂා කරන්න.',requestTimeout:'ඉල්ලීම කල් ඉකුත් විය. නැවත උත්සාහ කරන්න.',adminLoadFailed:'පරිපාලක දත්ත පූරණය අසාර්ථකයි',selfRoleBlocked:'ඇතුළු වී සිටියදී ඔබේම පරිපාලක භූමිකාව වෙනස් කළ නොහැක.',selfDeleteBlocked:'වත්මන් ගිණුම මකා දැමිය නොහැක.',roleChanged:'භූමිකාව සාර්ථකව වෙනස් විය',userDeleted:'පරිශීලකයා මකා දමන ලදී',roleChangeFailed:'භූමිකාව වෙනස් කිරීමට නොහැකි විය',userDeleteFailed:'පරිශීලකයා මැකීමට නොහැකි විය',historyHeading:'පුරෝකථන ඉතිහාසය',historyAll:'ඔබේ සියලු AI පුරෝකථන එකම ස්ථානයක',noRecordsExport:'අපනයනය කිරීමට වාර්තා නැත',pdfDownloaded:'PDF බාගත කරන ලදී',feedbackSaveFailed:'ප්‍රතිචාරය සුරැකීමට නොහැකි විය',predictionAccurateQuestion:'මෙම පුරෝකථනය නිවැරදිද?',yes:'ඔව්',no:'නැහැ',markedAccurate:'නිවැරදි ලෙස සලකන ලදී',feedbackRecorded:'ප්‍රතිචාරය සටහන් විය',lowConfidence:'අඩු විශ්වාස ප්‍රතිඵලයකි.',aiConfidence:'AI විශ්වාසය',forPaddy:'වී වගාව සඳහා',analysis:'විශ්ලේෂණය',notesLabel:'සටහන්',chemicalOption:'රසායනික විකල්පය',alerts:'අනතුරු ඇඟවීම්',howToUse:'භාවිතා කරන ආකාරය',profileSaved:'පැතිකඩ සුරකින ලදී!',profileSaveFailed:'පැතිකඩ සුරැකීමට නොහැකි විය.',invalidAvatar:'JPG, PNG හෝ WebP රූපයක් තෝරන්න',avatarTooLarge:'රූපය 5MB ට අඩු විය යුතුය',avatarProcessFailed:'රූපය සකස් කළ නොහැක. වෙනත් රූපයක් තෝරන්න.',deleteSuccess:'සාර්ථකව මකා දමන ලදී',operationFailed:'ක්‍රියාව අසාර්ථකයි. නැවත උත්සාහ කරන්න.',
    welcomeBack:'නැවත සාදරයෙන් පිළිගනිමු',createYourAccount:'ඔබේ ගිණුම සාදන්න',loginSub:'ඔබේ වී ක්ෂේත්‍ර කළමනාකරණයට ඇතුළු වන්න',registerSub:'නොමිලේ බුද්ධිමත්ව වගා කිරීම අරඹන්න',forgotPassword:'මුරපදය අමතකද?',dontHaveAccount:'ගිණුමක් නැද්ද?',alreadyHaveAccount:'දැනටමත් ගිණුමක් තිබේද?',signUp:'ලියාපදිංචි වන්න',showPassword:'මුරපදය පෙන්වන්න',hidePassword:'මුරපදය සඟවන්න',allUsers:'සියලු පරිශීලකයන්',allPredictions:'සියලු පුරෝකථන',type:'වර්ගය',userLabel:'පරිශීලකයා',unknownUser:'නොදන්නා පරිශීලකයා',unnamedUser:'නම නොමැති පරිශීලකයා',you:'ඔබ',loading:'පූරණය වෙමින්...',ratedAccurate:'නිවැරදි ලෙස ඇගයූ',total:'මුළු',successRateAll:'සාර්ථකත්ව අනුපාතය — සියලු මාදිලි',successRateHelp:'පහත පුරෝකථන සඳහා ඔබ ලබාදුන් නිරවද්‍යතා ප්‍රතිචාර මත',
    suitabilityResultLabel:'යෝග්‍යතා ප්‍රතිඵලය',diseaseScanResult:'රෝග ස්කෑන් ප්‍රතිඵලය',severityLevel:'බරපතලකම',recommendedFertilizerLabel:'නිර්දේශිත පොහොර',estimatedYieldLabel:'ඇස්තමේන්තුගත අස්වැන්න',pestRiskLabel:'පළිබෝධ අවදානම',chemicalOptionLabel:'රසායනික විකල්පය',organicOptionLabel:'කාබනික විකල්පය',seedling:'පැළ අවධිය',vegetative:'වර්ධන අවධිය',flowering:'මල් අවධිය',ripening:'පැසීමේ අවධිය',clay:'මැටි',loam:'ලෝම',sandy:'වැලි',profileStrength:'පැතිකඩ සම්පූර්ණතාව',saving:'සුරකිමින්...',editProfileHint:'විස්තර යාවත්කාලීන කිරීමට වම් පස පැතිකඩ සංස්කරණය ක්ලික් කරන්න',mlServerInactive:'Python ML සේවාදායකය ක්‍රියාත්මක නොවේ. AI පුරෝකථන සඳහා එය ආරම්භ කරන්න.',mlServerAfterStart:'ආරම්භ කළ පසු සේවාදායකය ක්‍රියාත්මක වන්නේ',cropManagement:'බෝග කළමනාකරණය',designedBy:'නිර්මාණය හා සංවර්ධනය',predictionCompleteMsg:'පුරෝකථනය සම්පූර්ණයි!',analysisCompleteMsg:'විශ්ලේෂණය සම්පූර්ණයි!',recommendationReadyMsg:'නිර්දේශය සූදානම්!',yieldEstimatedMsg:'අස්වැන්න ඇස්තමේන්තු කළා!',riskAssessedMsg:'අවදානම තක්සේරු කළා!',advisoryReadyMsg:'උපදේශනය සූදානම්!',predictionFailedMsg:'පුරෝකථනය අසාර්ථකයි.',

    makePredictionsChart:'ප්\u200dරස්ථාරය බැලීමට පුරෝකථන සිදු කරන්න',languageLabel:'භාෂාව',weeklyActivity7:'සතිපතා ක්\u200dරියාකාරිත්වය (පසුගිය දින 7)',predictionsThisWeek:'මෙම සතියේ පුරෝකථන',recentActivity:'මෑත ක්\u200dරියාකාරිත්වය',recentEmpty:'තවම පුරෝකථන නැත — ක්\u200dරියාකාරිත්වය බැලීමට යෝග්\u200dයතාව, රෝග හඳුනාගැනීම හෝ වාරි උපදෙස් උත්සාහ කරන්න.',allTime:'සියලු කාලය',landChecks:'ඉඩම් පරීක්ෂණ',leafScans:'කොළ ස්කෑන්',fieldAdvices:'ක්ෂේත්\u200dර උපදෙස්',recommendations:'නිර්දේශ',estimates:'ඇස්තමේන්තු',riskChecks:'අවදානම් පරීක්ෂණ',advisories:'උපදේශන',uploadPaddyLeafImage:'වී කොළ රූපයක් උඩුගත කරන්න',forgotSentPrefix:'ගිණුමක් තිබේ නම්',forgotSentSuffix:'මුරපදය නැවත සැකසීමට සබැඳියක් යවා ඇත. සබැඳිය මිනිත්තු 30කින් කල් ඉකුත් වේ.',emailExample:'you@example.com',exportPdf:'PDF අපනයනය',goodOutcome:'හොඳ ප්\u200dරතිඵලය — ක්\u200dරියාවක් අවශ්\u200dය නොවේ',attentionNeeded:'අවධානය අවශ්\u200dයයි',accurate:'නිවැරදි',inaccurate:'වැරදි',completeFarmDetails:'වඩා හොඳ AI නිර්දේශ සඳහා ගොවිපළ විස්තර සම්පූර්ණ කරන්න',soil:'පස',farmer:'ගොවියා',loadingProfile:'පැතිකඩ පූරණය වෙමින්…',cancel:'අවලංගු කරන්න',acres:'අක්කර',selectSoilType:'පස් වර්ගය තෝරන්න',describeFarmPlaceholder:'ඔබේ ගොවිපළ විස්තර කරන්න...',farmActivity:'ගොවිපළ ක්\u200dරියාකාරිත්වය',totalAiPredictions:'මුළු AI පුරෝකථන',lastActive:'අවසන් ක්\u200dරියාකාරිත්වය',farmNamePlaceholder:'උදා. කුරුණෑගල වී වගා බිම',farmLocationPlaceholder:'උදා. කුරුණෑගල, වයඹ පළාත',additionalNotesPlaceholder:'අමතර සටහන්...',activityDescriptionPlaceholder:'උදා. යූරියා 45kg/අක්කර යෙදීම',feedbackThanksAccurate:'ස්තුතියි! නිවැරදි ලෙස සලකන ලදී.',feedbackThanksRecorded:'ස්තුතියි! ඔබේ ප්\u200dරතිචාරය සටහන් විය.',aiFocusMap:'AI අවධානය යොමු කළ සිතියම (Grad-CAM)',aiFocusHelp:'රතු/කහ ප්\u200dරදේශ AI ආකෘතිය රෝග නිර්ණයේදී වැඩිපුර අවධානය යොමු කළ ස්ථාන පෙන්වයි.',symptomsToLookFor:'සොයා බැලිය යුතු ලක්ෂණ',treatmentGuide:'ප්\u200dරතිකාර මාර්ගෝපදේශය',step:'පියවර',preventionTips:'වැළැක්වීමේ උපදෙස්',uploadProfilePhoto:'පැතිකඩ ඡායාරූපය උඩුගත කරන්න',removePhoto:'ඡායාරූපය ඉවත් කරන්න',
    lowConfidenceHelp:'මෙම පුරෝකථනය ගැන AI විශ්වාසය අඩුයි (60% ට අඩු). දත්ත හෝ රූපය නැවත පරීක්ෂා කර වැදගත් ක්\u200dරියාමාර්ග සඳහා කෘෂිකර්ම නිලධාරියෙකු සමඟ තහවුරු කරන්න.',planted:'රෝපණය කළ දිනය',
    active:'සක්\u200dරීය',
  },
  ta: {
    appName:'Paddy AI System',appTagline:'இலங்கைக்கான AI பயிர் மேலாண்மை',
    dashboard:'டாஷ்போர்டு',suitability:'நில பொருத்தம்',disease:'நோய் கண்டறிதல்',
    irrigation:'நீர்ப்பாசனம்',history:'வரலாறு',logout:'வெளியேறு',profile:'சுயவிவரம்',
    login:'உள்நுழை',register:'பதிவு செய்',email:'மின்னஞ்சல்',password:'கடவுச்சொல்',
    fullName:'முழு பெயர்',namePlaceholder:'உங்கள் முழு பெயர்',emailPlaceholder:'farmer@example.com',
    passwordPlaceholder:'குறைந்தது 6 எழுத்துகள்',createAccount:'கணக்கை உருவாக்கு',signIn:'உள்நுழை',
    goodMorning:'காலை வணக்கம்',goodAfternoon:'மதிய வணக்கம்',goodEvening:'மாலை வணக்கம்',
    dashboardSub:'AI நெல் பயிர் மேலாண்மை — இலங்கை',
    quickAccess:'விரைவு அணுகல்',tryNow:'இப்போது முயற்சி செய்',
    suitabilityDesc:'உங்கள் நிலம் நெல் சாகுபடிக்கு ஏற்றதா',
    diseaseDesc:'நெல் நோய்களை கண்டறிய இலை படம் பதிவேற்றுங்கள்',
    irrigationDesc:'நீர்ப்பாசன பரிந்துரைகள் பெறுங்கள்',
    aboutSystem:'இந்த அமைப்பு பற்றி',
    aboutText:'இலங்கை நெல் விவசாயிகளுக்கான AI முடிவு ஆதரவு.',
    suitabilityTitle:'நெல் பொருத்தம் கணிப்பு',suitabilitySub:'நில பொருத்தம் சரிபார்க்க தரவை உள்ளிடுங்கள்',
    environmentParams:'சுற்றுச்சூழல் அளவுருக்கள்',temperature:'வெப்பநிலை (°C)',
    rainfall:'மழைப்பொழிவு (mm)',soilPh:'மண் pH',humidity:'ஈரப்பதம் (%)',soilType:'மண் வகை',
    predictSuitability:'பொருத்தத்தை கணி',predicting:'கணிக்கிறது...',idealConditions:'சிறந்த நிலைமைகள்',
    suitableResult:'நெல் சாகுபடிக்கு ஏற்றது',notSuitableResult:'ஏற்றதல்ல',
    riskLevel:'ஆபத்து நிலை',confidence:'நம்பகத்தன்மை',recommendation:'பரிந்துரை',
    diseaseTitle:'நெல் நோய் கண்டறிதல்',diseaseSub:'CNN மாதிரி நோயை கண்டறியும்',
    uploadImage:'இலை படம் பதிவேற்று',detectDisease:'நோயை கண்டறி',detecting:'பகுப்பாய்வு...',
    detectedDisease:'கண்டறியப்பட்ட நோய்',healthyLeaf:'ஆரோக்கியமான இலை',severity:'தீவிரம்',
    treatment:'சிகிச்சை',prevention:'தடுப்பு',detectableDiseases:'கண்டறியக்கூடிய நோய்கள்',
    dragDrop:'நெல் இலை படத்தை இழுத்து விடுங்கள்',browseImage:'படம் தேர்வு',imageReady:'படம் தயார்',
    irrigationTitle:'நீர்ப்பாசன பரிந்துரை',irrigationSub:'வயல் நிலைமைகளை உள்ளிடுங்கள்',
    fieldConditions:'வயல் நிலைமைகள்',soilMoisture:'மண் ஈரப்பதம் (%)',cropStage:'பயிர் வளர்ச்சி நிலை',
    getAdvice:'நீர்ப்பாசன ஆலோசனை',analyzing:'பகுப்பாய்வு...',
    irrigationStatus:'நீர்ப்பாசன நிலை',irrigationRequired:'நீர்ப்பாசனம் தேவை',
    noIrrigation:'நீர்ப்பாசனம் தேவையில்லை',urgency:'அவசரம்',
    recommendedWater:'பரிந்துரைக்கப்பட்ட நீர்',nextCheck:'அடுத்த சோதனை',waterNeeds:'நீர் தேவை',
    historyTitle:'கணிப்பு வரலாறு',historySub:'அனைத்து AI கணிப்புகள்',
    noPredictions:'இன்னும் கணிப்புகள் இல்லை.',predictionResult:'கணிப்பு முடிவு',
    fillForm:'படிவத்தை நிரப்பி கிளிக் செய்யுங்கள்',result:'முடிவு',days:'நாள்(கள்)',mm:'மி.மீ',
    records:'பதிவுகள்',successRate:'வெற்றி விகிதம்',weeklyActivity:'வாராந்திர செயல்பாடு',
    last7days:'கடந்த 7 நாட்கள்',predictions:'கணிப்புகள்',totalPredictions:'மொத்த கணிப்புகள்',
    myProfile:'என் சுயவிவரம்',profileSub:'உங்கள் பண்ணை சுயவிவரத்தை நிர்வகிக்கவும்',
    editProfile:'சுயவிவரம் திருத்து',saveProfile:'சுயவிவரம் சேமி',farmDetails:'பண்ணை விவரங்கள்',
    farmLocation:'பண்ணை இடம்',farmSize:'பண்ணை அளவு',farmBio:'பண்ணை விளக்கம்',
    fertilizer:'உரம்',fertilizerTitle:'உர பரிந்துரை',fertilizerSub:'சிறந்த உரத்திற்கு மண் மற்றும் ஊட்டச்சத்து தரவை உள்ளிடவும்',
    soilNutrientParams:'மண் மற்றும் ஊட்டச்சத்து அளவுருக்கள்',
    nitrogen:'நைட்ரஜன் (N)',potassium:'பொட்டாசியம் (K)',phosphorous:'பாஸ்பரஸ் (P)',
    getFertilizerAdvice:'உர ஆலோசனை பெறுங்கள்',recommendedFertilizer:'பரிந்துரைக்கப்பட்ட உரம்',
    quantityRequired:'தேவையான அளவு',applicationSchedule:'பயன்பாட்டு அட்டவணை',organicAlternative:'இயற்கை மாற்று',
    yield:'மகசூல் கணிப்பு',yieldTitle:'நெல் மகசூல் கணிப்பு',yieldSub:'மகசூலை மதிப்பிட சாகுபடி தரவை உள்ளிடவும்',
    cultivationParams:'சாகுபடி அளவுருக்கள்',fertilizerUsed:'பயன்படுத்திய உரம் (kg/ஏக்கர்)',
    seedVariety:'விதை வகை',irrigationPattern:'நீர்ப்பாசன முறை',diseaseStatus:'நோய் நிலை',soilQuality:'மண் தரம்',
    predictYield:'மகசூலை கணி',estimatedYield:'மதிப்பிடப்பட்ட மகசூல்',expectedHarvest:'எதிர்பார்க்கப்படும் அறுவடை',productionEfficiency:'உற்பத்தி திறன்',
    pest:'பூச்சி அபாயம்',pestTitle:'பூச்சி அபாய கணிப்பு',pestSub:'பூச்சி அபாயத்தை மதிப்பிட வயல் நிலைமைகளை உள்ளிடவும்',
    rainfall7d:'கடந்த 7 நாட்களின் மழை (mm)',checkPestRisk:'பூச்சி அபாயத்தை சரிபார்',pestRiskLevel:'பூச்சி அபாய நிலை',
    mostLikelyPest:'வாய்ப்புள்ள பூச்சி',preventionMeasures:'தடுப்பு நடவடிக்கைகள்',recommendedPesticide:'பரிந்துரைக்கப்பட்ட பூச்சிக்கொல்லி',organicOption:'இயற்கை விருப்பம்',
    fertilizerDesc:'NPK அடிப்படையிலான உர பரிந்துரைகளைப் பெறுங்கள்',yieldDesc:'உங்கள் எதிர்பார்க்கப்படும் மகசூலை மதிப்பிடுங்கள்',pestDesc:'உங்கள் வயலுக்கான பூச்சி அபாயத்தை மதிப்பிடுங்கள்',
    weather:'வானிலை ஆலோசனை',weatherTitle:'வானிலை அடிப்படையிலான விவசாய ஆலோசனை',weatherSub:'வானிலை அடிப்படையில் நடவு, உரம் மற்றும் நீர்ப்பாசன வழிகாட்டுதலைப் பெறுங்கள்',
    weatherConditions:'வானிலை நிலைமைகள்',rainfallForecast:'மழை முன்னறிவிப்பு (mm)',getWeatherAdvisory:'வானிலை ஆலோசனை பெறுங்கள்',
    bestPlantingTime:'நடவு ஆலோசனை',fertilizerTiming:'உர நேரம்',irrigationTiming:'நீர்ப்பாசன நேரம்',harvestPlanning:'அறுவடை திட்டமிடல்',weatherAlerts:'எச்சரிக்கைகள்',
    weatherDesc:'வானிலை அடிப்படையிலான நடவு, உரம் மற்றும் நீர்ப்பாசன வழிகாட்டுதல்',farmManagement:'எனது பண்ணைகள்',
adminPanel:'நிர்வாக பலகம்',administrator:'நிர்வாகி',systemAdministration:'அமைப்பு நிர்வாகம்',adminSub:'பயனர்கள், AI கணிப்புகள் மற்றும் பயன்பாட்டு சேவைகளை நிர்வகிக்கவும்.',overview:'மேலோட்டம்',users:'பயனர்கள்',refresh:'புதுப்பி',predictionBreakdown:'கணிப்பு பகுப்பாய்வு',serviceConfiguration:'சேவை அமைப்பு',recentPredictions:'சமீபத்திய கணிப்புகள் (கடைசி 10)',noAdminPredictions:'இன்னும் கணிப்புகள் இல்லை.',totalUsers:'மொத்த பயனர்கள்',registeredAccounts:'பதிவு செய்யப்பட்ட கணக்குகள்',allModelTypes:'அனைத்து மாதிரி வகைகள்',diseaseScans:'நோய் ஸ்கேன்',leafImageScans:'இலை படம் ஸ்கேன்',farmerValidatedAccuracy:'விவசாயி உறுதிப்படுத்திய துல்லியம்',noFeedbackYet:'இன்னும் கருத்து இல்லை',name:'பெயர்',role:'பங்கு',joined:'சேர்ந்த தேதி',actions:'செயல்கள்',promote:'உயர்த்து',demote:'தாழ்த்து',delete:'நீக்கு',status:'நிலை',javaBackend:'Java பின்சேவை',reactFrontend:'React முன்சேவை',mysqlDb:'MySQL தரவுத்தளம்',pythonMlApi:'Python ML API',responding:'பதிலளிக்கிறது',currentApp:'தற்போதைய செயலி',backendConnected:'பின்சேவை இணைந்தது',usedOnPredictions:'கணிப்புகளில் பயன்படும்',notifications:'அறிவிப்புகள்',markAllRead:'அனைத்தையும் வாசித்ததாக குறி',noNotifications:'அறிவிப்புகள் இல்லை',justNow:'இப்போது',farmManagementTitle:'பண்ணை மேலாண்மை',myFarms:'எனது பண்ணைகள்',farmManagementSub:'வயல்களை பதிவு செய்து பயிர் செயல்பாடுகளை கண்காணிக்கவும்',addFarm:'பண்ணை சேர்',editFarm:'பண்ணை திருத்து',newFarm:'புதிய பண்ணை',farmName:'பண்ணை பெயர்',location:'இடம்',sizeAcres:'அளவு (ஏக்கர்)',currentCropVariety:'தற்போதைய பயிர் வகை',plantingDate:'நடவு தேதி',notes:'குறிப்புகள்',saveChanges:'மாற்றங்களை சேமி',loadingFarms:'பண்ணைகள் ஏற்றப்படுகின்றன...',noFarms:'இன்னும் பண்ணைகள் பதிவு செய்யப்படவில்லை.',viewActivities:'செயல்பாடுகளைப் பார்',activitiesShown:'செயல்பாடுகள் கீழே',activityLog:'செயல்பாட்டு பதிவு',logActivity:'செயல்பாட்டை பதிவு செய்',activityType:'செயல்பாட்டு வகை',date:'தேதி',description:'விளக்கம்',saveActivity:'செயல்பாட்டை சேமி',noActivities:'இன்னும் செயல்பாடுகள் இல்லை.',farmAdded:'பண்ணை சேர்க்கப்பட்டது!',farmUpdated:'பண்ணை புதுப்பிக்கப்பட்டது!',farmDeleted:'பண்ணை நீக்கப்பட்டது',activityLogged:'செயல்பாடு பதிவு செய்யப்பட்டது!',activityDeleted:'செயல்பாடு நீக்கப்பட்டது',failedSaveFarm:'பண்ணையை சேமிக்க முடியவில்லை.',failedDeleteFarm:'பண்ணையை நீக்க முடியவில்லை.',failedLogActivity:'செயல்பாட்டை பதிவு செய்ய முடியவில்லை.',failedDeleteActivity:'செயல்பாட்டை நீக்க முடியவில்லை.',confirmDeleteFarm:'இந்த பண்ணை மற்றும் அனைத்து செயல்பாட்டு பதிவுகளையும் நீக்கவா?',confirmDeleteUser:'இந்த பயனர் மற்றும் தொடர்புடைய தரவுகளை நீக்கவா?',invalidDiseaseFile:'JPG, JPEG, PNG அல்லது WebP படங்கள் மட்டுமே ஏற்றுக்கொள்ளப்படும்.',imageTooLarge:'படம் 5 MB அல்லது அதற்கு குறைவாக இருக்க வேண்டும்.',selectLeafFirst:'முதலில் நெல் இலை படத்தைத் தேர்ந்தெடுக்கவும்.',diseaseComplete:'நோய் பகுப்பாய்வு முடிந்தது!',detectionFailed:'கண்டறிதல் தோல்வியடைந்தது.',mlServerDown:'ML சேவையகம் இயங்கவில்லை. Python சேவையை port 8000-ல் தொடங்கவும்.',supportedImages:'JPG · JPEG · PNG · WebP ஏற்கப்படும்',or:'அல்லது',betterScanTips:'சிறந்த ஸ்கேன் குறிப்புகள்',scanTip1:'பிரகாசமான இயற்கை வெளிச்சத்தில் படம் எடுக்கவும்',scanTip2:'பாதிக்கப்பட்ட இலை பகுதியை தெளிவாக கவனம் செலுத்தவும்',scanTip3:'மங்கலான அல்லது இருண்ட படங்களை தவிர்க்கவும்',scanTip4:'சிறந்த துல்லியத்திற்கு ஒரு இலையை மட்டும் பயன்படுத்தவும்',uploadPrompt:'நெல் இலை படத்தை பதிவேற்றி நோய் கண்டறி என்பதைக் கிளிக் செய்யவும்',cnnAnalyze:'CNN மாதிரி இலையை பகுப்பாய்வு செய்யும்',changeImage:'படத்தை மாற்று',remove:'அகற்று',forgotTagline:'கடவுச்சொல் மறந்துவிட்டதா?',backToSignIn:'உள்நுழைவுக்கு திரும்பு',checkInbox:'உங்கள் மின்னஞ்சலை பார்க்கவும்',resetPassword:'கடவுச்சொல்லை மீட்டமை',resetHelp:'உங்கள் மின்னஞ்சலை உள்ளிடுங்கள்; கணக்கிற்கு திரும்ப இணைப்பை அனுப்புவோம்.',sendResetLink:'மீட்டமைப்பு இணைப்பை அனுப்பு',tryAgain:'கிடைக்கவில்லையா? மீண்டும் முயற்சி செய்',resetEmailSent:'கடவுச்சொல் மீட்டமைப்பு கோரிக்கை அனுப்பப்பட்டது.',invalidResetTagline:'இணைப்பு தவறாக உள்ளது',invalidResetLink:'தவறான மீட்டமைப்பு இணைப்பு',invalidResetHelp:'இந்த இணைப்பில் reset token இல்லை. புதிய இணைப்பை கோரவும்.',requestNewLink:'புதிய இணைப்பை கோரு',setNewPassword:'புதிய கடவுச்சொல் அமை',passwordResetDone:'கடவுச்சொல் மீட்டமைக்கப்பட்டது!',passwordChanged:'உங்கள் கடவுச்சொல் வெற்றிகரமாக மாற்றப்பட்டது.',createNewPassword:'புதிய கடவுச்சொல் உருவாக்கு',strongPasswordHelp:'குறைந்தது 6 எழுத்துகள் இருக்க வேண்டும்.',newPassword:'புதிய கடவுச்சொல்',confirmNewPassword:'புதிய கடவுச்சொல்லை உறுதிப்படுத்து',passwordsMismatch:'கடவுச்சொற்கள் பொருந்தவில்லை.',passwordMin:'கடவுச்சொல் குறைந்தது 6 எழுத்துகள் இருக்க வேண்டும்.',resetFailed:'கடவுச்சொல்லை மீட்டமைக்க முடியவில்லை. இணைப்பு காலாவதியாகியிருக்கலாம்.',sessionExpired:'உங்கள் அமர்வு காலாவதியானது. மீண்டும் உள்நுழையவும்.',networkError:'சேவையகத்தை அணுக முடியவில்லை. Backend இயங்குகிறதா பார்க்கவும்.',requestTimeout:'கோரிக்கை நேரம் முடிந்தது. மீண்டும் முயற்சி செய்யவும்.',adminLoadFailed:'நிர்வாக தரவை ஏற்ற முடியவில்லை',selfRoleBlocked:'உள்நுழைந்திருக்கும்போது உங்கள் நிர்வாக பங்கை மாற்ற முடியாது.',selfDeleteBlocked:'தற்போதைய கணக்கை நீக்க முடியாது.',roleChanged:'பங்கு வெற்றிகரமாக மாற்றப்பட்டது',userDeleted:'பயனர் நீக்கப்பட்டார்',roleChangeFailed:'பங்கை மாற்ற முடியவில்லை',userDeleteFailed:'பயனரை நீக்க முடியவில்லை',historyHeading:'கணிப்பு வரலாறு',historyAll:'உங்கள் அனைத்து AI கணிப்புகளும் ஒரே இடத்தில்',noRecordsExport:'ஏற்றுமதி செய்ய பதிவுகள் இல்லை',pdfDownloaded:'PDF பதிவிறக்கப்பட்டது',feedbackSaveFailed:'கருத்தை சேமிக்க முடியவில்லை',predictionAccurateQuestion:'இந்த கணிப்பு துல்லியமானதா?',yes:'ஆம்',no:'இல்லை',markedAccurate:'துல்லியமாக குறிக்கப்பட்டது',feedbackRecorded:'கருத்து பதிவு செய்யப்பட்டது',lowConfidence:'குறைந்த நம்பிக்கை முடிவு.',aiConfidence:'AI நம்பிக்கை',forPaddy:'நெல் சாகுபடிக்காக',analysis:'பகுப்பாய்வு',notesLabel:'குறிப்புகள்',chemicalOption:'ரசாயன விருப்பம்',alerts:'எச்சரிக்கைகள்',howToUse:'பயன்படுத்துவது எப்படி',profileSaved:'சுயவிவரம் சேமிக்கப்பட்டது!',profileSaveFailed:'சுயவிவரத்தை சேமிக்க முடியவில்லை.',invalidAvatar:'JPG, PNG அல்லது WebP படத்தைத் தேர்ந்தெடுக்கவும்',avatarTooLarge:'படம் 5MB-க்கு குறைவாக இருக்க வேண்டும்',avatarProcessFailed:'படத்தை செயலாக்க முடியவில்லை. வேறு படத்தைத் தேர்ந்தெடுக்கவும்.',deleteSuccess:'வெற்றிகரமாக நீக்கப்பட்டது',operationFailed:'செயல் தோல்வியடைந்தது. மீண்டும் முயற்சி செய்யவும்.',
    welcomeBack:'மீண்டும் வரவேற்கிறோம்',createYourAccount:'உங்கள் கணக்கை உருவாக்குங்கள்',loginSub:'உங்கள் நெல் வயல்களை நிர்வகிக்க உள்நுழையவும்',registerSub:'இலவசமாக புத்திசாலித்தனமாக வளரத் தொடங்குங்கள்',forgotPassword:'கடவுச்சொல் மறந்துவிட்டதா?',dontHaveAccount:'கணக்கு இல்லையா?',alreadyHaveAccount:'ஏற்கனவே கணக்கு உள்ளதா?',signUp:'பதிவு செய்',showPassword:'கடவுச்சொல்லைக் காட்டு',hidePassword:'கடவுச்சொல்லை மறை',allUsers:'அனைத்து பயனர்கள்',allPredictions:'அனைத்து கணிப்புகள்',type:'வகை',userLabel:'பயனர்',unknownUser:'தெரியாத பயனர்',unnamedUser:'பெயரிடாத பயனர்',you:'நீங்கள்',loading:'ஏற்றுகிறது...',ratedAccurate:'துல்லியமாக மதிப்பிடப்பட்டது',total:'மொத்தம்',successRateAll:'வெற்றி விகிதம் — அனைத்து மாதிரிகள்',successRateHelp:'கீழே உள்ள ஒவ்வொரு கணிப்பிற்கும் நீங்கள் அளித்த துல்லிய கருத்தின் அடிப்படையில்',
    suitabilityResultLabel:'பொருத்த முடிவு',diseaseScanResult:'நோய் ஸ்கேன் முடிவு',severityLevel:'தீவிர நிலை',recommendedFertilizerLabel:'பரிந்துரைக்கப்பட்ட உரம்',estimatedYieldLabel:'மதிப்பிடப்பட்ட மகசூல்',pestRiskLabel:'பூச்சி அபாய நிலை',chemicalOptionLabel:'ரசாயன விருப்பம்',organicOptionLabel:'இயற்கை விருப்பம்',seedling:'நாற்று நிலை',vegetative:'வளர்ச்சி நிலை',flowering:'மலர்ச்சி நிலை',ripening:'முதிர்ச்சி நிலை',clay:'களிமண்',loam:'லோம்',sandy:'மணல்',profileStrength:'சுயவிவர நிறைவு',saving:'சேமிக்கிறது...',editProfileHint:'விவரங்களைப் புதுப்பிக்க இடப்புறத்தில் சுயவிவரத்தை திருத்து என்பதைக் கிளிக் செய்யவும்',mlServerInactive:'Python ML சேவையகம் செயல்படவில்லை. AI கணிப்புகளுக்கு அதை தொடங்கவும்.',mlServerAfterStart:'தொடங்கிய பின் சேவையகம் இயங்கும் முகவரி',cropManagement:'பயிர் மேலாண்மை',designedBy:'வடிவமைத்து உருவாக்கியது',predictionCompleteMsg:'கணிப்பு முடிந்தது!',analysisCompleteMsg:'பகுப்பாய்வு முடிந்தது!',recommendationReadyMsg:'பரிந்துரை தயாராக உள்ளது!',yieldEstimatedMsg:'மகசூல் மதிப்பிடப்பட்டது!',riskAssessedMsg:'அபாயம் மதிப்பிடப்பட்டது!',advisoryReadyMsg:'ஆலோசனை தயாராக உள்ளது!',predictionFailedMsg:'கணிப்பு தோல்வியடைந்தது.',

    makePredictionsChart:'வரைபடத்தைப் பார்க்க கணிப்புகளைச் செய்யவும்',languageLabel:'மொழி',weeklyActivity7:'வாராந்திர செயல்பாடு (கடந்த 7 நாட்கள்)',predictionsThisWeek:'இந்த வார கணிப்புகள்',recentActivity:'சமீபத்திய செயல்பாடு',recentEmpty:'இன்னும் கணிப்புகள் இல்லை — செயல்பாட்டைக் காண நில பொருத்தம், நோய் கண்டறிதல் அல்லது நீர்ப்பாசனத்தை முயற்சிக்கவும்.',allTime:'எல்லா காலமும்',landChecks:'நில சோதனைகள்',leafScans:'இலை ஸ்கேன்கள்',fieldAdvices:'வயல் ஆலோசனைகள்',recommendations:'பரிந்துரைகள்',estimates:'மதிப்பீடுகள்',riskChecks:'அபாய சோதனைகள்',advisories:'ஆலோசனைகள்',uploadPaddyLeafImage:'நெல் இலை படத்தை பதிவேற்றவும்',forgotSentPrefix:'கணக்கு இருந்தால்',forgotSentSuffix:'கடவுச்சொல்லை மீட்டமைக்கும் இணைப்பு அனுப்பப்பட்டுள்ளது. இணைப்பு 30 நிமிடங்களில் காலாவதியாகும்.',emailExample:'you@example.com',exportPdf:'PDF ஏற்றுமதி',goodOutcome:'நல்ல முடிவு — நடவடிக்கை தேவையில்லை',attentionNeeded:'கவனம் தேவை',accurate:'துல்லியம்',inaccurate:'தவறு',completeFarmDetails:'சிறந்த AI பரிந்துரைகளுக்கு பண்ணை விவரங்களை நிறைவு செய்யவும்',soil:'மண்',farmer:'விவசாயி',loadingProfile:'சுயவிவரம் ஏற்றப்படுகிறது…',cancel:'ரத்து செய்',acres:'ஏக்கர்',selectSoilType:'மண் வகையைத் தேர்வு செய்',describeFarmPlaceholder:'உங்கள் பண்ணையை விவரிக்கவும்...',farmActivity:'பண்ணை செயல்பாடு',totalAiPredictions:'மொத்த AI கணிப்புகள்',lastActive:'கடைசி செயல்பாடு',farmNamePlaceholder:'உதா. குருநாகல் நெல் வயல்',farmLocationPlaceholder:'உதா. குருநாகல், வடமேற்கு மாகாணம்',additionalNotesPlaceholder:'கூடுதல் குறிப்புகள்...',activityDescriptionPlaceholder:'உதா. யூரியா 45kg/ஏக்கர் பயன்படுத்தப்பட்டது',feedbackThanksAccurate:'நன்றி! துல்லியமாகக் குறிக்கப்பட்டது.',feedbackThanksRecorded:'நன்றி! உங்கள் கருத்து பதிவு செய்யப்பட்டது.',aiFocusMap:'AI கவன வரைபடம் (Grad-CAM)',aiFocusHelp:'சிவப்பு/மஞ்சள் பகுதிகள் நோய் கண்டறியும் போது AI அதிகமாக கவனம் செலுத்திய இடங்களை காட்டுகின்றன.',symptomsToLookFor:'கவனிக்க வேண்டிய அறிகுறிகள்',treatmentGuide:'சிகிச்சை வழிகாட்டி',step:'படி',preventionTips:'தடுப்பு குறிப்புகள்',uploadProfilePhoto:'சுயவிவர படத்தை பதிவேற்று',removePhoto:'படத்தை அகற்று',
    lowConfidenceHelp:'இந்த கணிப்பில் AI நம்பிக்கை குறைவாக உள்ளது (60% க்குக் கீழே). உள்ளீடு அல்லது படத்தை மீண்டும் சரிபார்த்து, முக்கிய நடவடிக்கைகளை உள்ளூர் வேளாண்மை அலுவலருடன் உறுதிப்படுத்தவும்.',planted:'நடவு செய்த தேதி',
    active:'செயலில்',
  }
}

const LanguageContext = createContext(null)

export function LanguageProvider({ children }) {
  const [lang, setLang] = useState(() => localStorage.getItem('paddy_lang') || 'en')
  useEffect(() => { document.documentElement.lang = lang }, [lang])
  const t = key => T[lang]?.[key] || T['en']?.[key] || key
  const changeLang = l => { setLang(l); localStorage.setItem('paddy_lang', l) }
  return <LanguageContext.Provider value={{ lang, changeLang, t }}>{children}</LanguageContext.Provider>
}

export function useLang() {
  const ctx = useContext(LanguageContext)
  if (!ctx) return { lang: 'en', changeLang: () => {}, t: k => T['en']?.[k] || k }
  return ctx
}
